backend:
  name: git-gateway
  repo: razroo/angular-the-full-gamut-markdown
  branch: laurell-RD-1
  base_url: "https://angular-the-full-gamut-markdown.netlify.app"

publish_mode: editorial_workflow

media_folder: "content/static/public/images"
public_folder: "/content/images/uploads"

collections:
- label: "Architecture" # Used in the UI
  name: "architecture" # Used in routes, e.g., /admin/collections/blog
  folder: "architecture" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: "name"
  nested:
    depth: 100
    summary: "{{meta.path}}"
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Code Examples" # Used in the UI
  name: "code-examples" # Used in routes, e.g., /admin/collections/blog
  folder: "code-examples" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Core" # Used in the UI
  name: "core" # Used in routes, e.g., /admin/collections/blog
  folder: "core" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Design Language System" # Used in the UI
  name: "design-language-system" # Used in routes, e.g., /admin/collections/blog
  folder: "design-language-system" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Dev Tools" # Used in the UI
  name: "dev-tools" # Used in routes, e.g., /admin/collections/blog
  folder: "dev-tools" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Graphics" # Used in the UI
  name: "graphics" # Used in routes, e.g., /admin/collections/blog
  folder: "graphics" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Introduction" # Used in the UI
  name: "introduction" # Used in routes, e.g., /admin/collections/blog
  folder: "introduction" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Libs" # Used in the UI
  name: "libs" # Used in routes, e.g., /admin/collections/blog
  folder: "libs" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Miscellaneous" # Used in the UI
  name: "miscellaneous" # Used in routes, e.g., /admin/collections/blog
  folder: "miscellaneous" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Performance" # Used in the UI
  name: "performance" # Used in routes, e.g., /admin/collections/blog
  folder: "performance" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "PWA" # Used in the UI
  name: "pwa" # Used in routes, e.g., /admin/collections/blog
  folder: "pwa" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "RxJS" # Used in the UI
  name: "rxjs" # Used in routes, e.g., /admin/collections/blog
  folder: "rxjs" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "State" # Used in the UI
  name: "state" # Used in routes, e.g., /admin/collections/blog
  folder: "state" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }


- label: "TypeScript" # Used in the UI
  name: "typescript" # Used in routes, e.g., /admin/collections/blog
  folder: "typescript" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }

- label: "Unit Testing" # Used in the UI
  name: "unit-testing" # Used in routes, e.g., /admin/collections/blog
  folder: "unit-testing" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  identifier_field: name
  nested:
    depth: 100
  fields:
      - {label: "Body", name: "body", widget: "markdown"}
  meta: { path: { widget: string, label: 'Path', index_file: "{{slug}}" } }
